consumes:
  - application/json
info:
  description: HTTP server in Go with Swagger endpoints definition
  title: survey-webapp-backend
  version: 0.1.0
produces:
  - application/json
schemes:
  - http
swagger: "2.0"

paths:
  /users/{id}:
    get:
      parameters:
        - description: User ID
          in: path
          name: id
          required: true
          type: integer
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: string
        404:
          description: User not found
      security:
        - ApiKeyAuth: []
      summary: Retrieves user based on given ID
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
