http:
  port: 8080
db:
  dbtype: "sqlite3"
  dburl: "local.db"
  maxIdleConns: 1
  maxOpenConns: 1
  connMaxLifetime: "1h"
security:
  resource: "local"
  secretKey: "mysecret"
smtp:
  server: "smtp.gmail.com"
  email: "CHANGE_TO_YOUR_EMAIL@gmail.com"
  password: "YOUR_PASSWORD"
  port: 587
